### ISSUE TITLE
Error of `demo.m`

### ISSUE THREAD

**Issue by zzf495** [BBKing49/OMFC-CS#1]
hi there, I hope this finds you well.

I saw your outstanding work on website and I am looking forward to delving into your work. But I found an error in `demo.m`, where "too much outputs" occurs when calling " [U, V, w, Hs, Hc, loss] = MVFCM_JRLCP(data,option)". I changed the code to "[U, V, Hs, Hc, loss] = MVFCM_JRLCP(data,option)", which makes it work properly. 

As a study, I would like to ask if you can disclose the details of "MVFCM_JRLCP.m"?

**Comment by BBKing49** [comment]
Thanks for your attention to our work, and we have corrected this small error.

There is currently follow-up work based on this code, so full details cannot be disclosed at this time.

**Comment by zzf495** [comment]
Thank you for responding. I am eagerly anticipating the release of your latest findings!
